---

- name: Installing packages
  package:
    name: "{{ htpasswd_packages }}"

- name: Installing python packages
  pip:
    name: "{{ htpasswd_pip_packages }}"

- name: Creating htpasswd folder
  file:
    dest: "{{ htpasswd_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: not((htpasswd_path is undefined) or (htpasswd_path is none) or (htpasswd_path|length == 0))
